### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.eps,*.ts -L abov,alph,ba,cleare,datas,fo,gir,inout,ist,manualy,nd,pard,te,ue,varn,vectore`

### CODE REVIEW

**Comment by luzpaz** [comment]
Commit 41e78ff may break API. Please examine closely

**Comment by felix-salfelder** [comment]
Thanks. Could you isolate the non-interface changes *or* make the interface changes backwards comptible (misspelled alias, but display a warning or so). Or just leave it like that...

"euclidean" (the non-code occurences) should it not be capitalised?

**Comment by luzpaz** [comment]
Hi, @felix-salfelder. So just to be clear what you're referring to as interface changes is: 41e78ff  
Right?

I don't know how to add backward compatible logic, sorry :disappointed:   
`euclidean` can be however your prefer. (I've seen it lowercase in a lot of of other projects)

**Comment by felix-salfelder** [comment]
On Mon, Aug 09, 2021 at 04:28:47AM -0700, luzpaz wrote:
> Hi, @felix-salfelder. So just to be clear what you're referring to as interface changes is: 41e78ff  
> Right?

Interface changes are the changes to the names of publically visible
symbols. I'd rather not touch this without a compelling reason.

Some of 41e78ff are interface changes. 41e78ff~1 appears to be comments
only (good).

> I don't know how to add backward compatible logic, sorry :disappointed:

You don't have to, I think your changes are worthwile anyhow.

> `euclidean` can be however your prefer. (I've seen it lowercase in a lot of of other projects)

My preference was Euclidean, but I don't mind. Wikipedia says even
"Euclidian" exist, but less common. I had never seen that, nor has your
spell checker.

Please squash into a single commit with comment fixes only. I will merge
it after a closer look.

**Comment by luzpaz** [comment]
Dropped commit and force pushed only the source comment changes as you requested, @felix-salfelder

**Pull request merged**
